package api

import (
	"context"
	"os"
	"strconv"
	"strings"
	"time"

	"monopanel/internal/agent"
)

// nginx listens on the addresses of the sites and of the default servers by
// name, IPv6 ones included. An address that comes from router advertisements
// or DHCPv6 is not on the interface yet when nginx starts at boot: bind()
// answers "Cannot assign requested address", nginx exits, and with no restart
// in its unit every site stays down until someone starts it by hand. Two
// things keep the host out of that state:
//
//   - net.ipv6.ip_nonlocal_bind lets a socket bind an IPv6 address before the
//     host has it, so the start does not depend on how fast the address
//     arrives;
//   - a drop-in restarts nginx when a start does fail, and removes a pid file
//     left with a foreign SELinux label (nginx -t run by the agent while
//     nginx is down creates it as var_run_t, which nginx may not open).
const (
	nginxSysctlPath = "/etc/sysctl.d/90-monopanel.conf"
	nginxSysctl     = "# Generated by MonoPanel: nginx binds the sites' IPv6 addresses by name, and at boot\n# an address from router advertisements or DHCPv6 may not be on the interface yet.\nnet.ipv6.ip_nonlocal_bind = 1\n"
	nginxDropIn     = `# Generated by MonoPanel: a failed start (an address not there yet, a pid file
# with a foreign SELinux label) is retried instead of leaving the sites down.
[Unit]
StartLimitIntervalSec=300
StartLimitBurst=20

[Service]
ExecStartPre=-/usr/bin/rm -f /run/nginx.pid
Restart=on-failure
RestartSec=5s
`
)

func (s *Server) nginxDropInPath() string {
	return unitDir + "/" + s.profile.Web().NginxService + ".d/monopanel.conf"
}

// ensureNginxBoot writes the sysctl and the drop-in; systemd and the kernel
// hear about them only when a file actually changed.
func (s *Server) ensureNginxBoot(ctx context.Context) error {
	res, err := s.agent.ApplyConfigSet(ctx, &agent.ApplyConfigSetRequest{Files: []agent.FileSpec{
		{Path: nginxSysctlPath, Content: nginxSysctl, Mode: 0o644},
		{Path: s.nginxDropInPath(), Content: nginxDropIn, Mode: 0o644},
	}, Origin: "stack:nginx-boot"})
	if err != nil {
		return err
	}
	if len(res.Written) == 0 {
		return nil
	}
	if _, err := s.agent.Service(ctx, "", "daemon-reload"); err != nil {
		return err
	}
	// systemd-sysctl applies /etc/sysctl.d; the agent itself may not write
	// /proc/sys (ProtectKernelTunables).
	_, err = s.agent.Service(ctx, "systemd-sysctl.service", "restart")
	return err
}

// uptimePath is /proc/uptime; tests point it elsewhere.
var uptimePath = "/proc/uptime"

// justBooted reports whether the host came up less than d ago: the network
// may not have all its addresses yet, so their absence proves nothing.
func justBooted(d time.Duration) bool {
	raw, err := os.ReadFile(uptimePath)
	if err != nil {
		return false
	}
	f := strings.Fields(string(raw))
	if len(f) == 0 {
		return false
	}
	up, err := strconv.ParseFloat(f[0], 64)
	return err == nil && time.Duration(up*float64(time.Second)) < d
}
