package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"path"
	"regexp"
	"strings"

	"github.com/danielgtaylor/huma/v2"

	"monopanel/internal/agent"
	"monopanel/internal/apitypes"
	"monopanel/internal/jobs"
	"monopanel/internal/store"
)

// A shared folder: one account's site folder reachable by another account
// over SFTP. Changing the guest's home to a path inside the owner's site is
// what people ask for, and it cannot work — sshd wants the chroot owned by
// root and the panel wants every home under /var/www/<login>. So the guest
// keeps its home, the folder is bind-mounted into it by a systemd mount unit,
// and ACLs on the folder let both accounts (and the web server) use the
// files. The guest sees the folder after signing in and nothing else.

var sharePathRe = regexp.MustCompile(`^[A-Za-z0-9._-]+(/[A-Za-z0-9._-]+)*$`)

type shareListOutput struct {
	Body []*apitypes.ShareStatus
}

type shareOutput struct {
	Status int
	Body   *apitypes.ShareStatus
}

type shareCreateInput struct {
	Login string `path:"login"`
	Body  apitypes.ShareRequest
}

type shareNameInput struct {
	Login string `path:"login"`
	Name  string `path:"name"`
}

type shareUpdateInput struct {
	Login string `path:"login"`
	Name  string `path:"name"`
	Body  apitypes.ShareUpdate
}

// sharePaths is where the folder is (in the owner's site) and where the
// guest sees it (in its own home).
func (s *Server) sharePaths(ctx context.Context, sh *store.Share) (target, where string, err error) {
	guest, err := s.db.GetUserByID(ctx, sh.UserID)
	if err != nil {
		return "", "", err
	}
	site, err := s.db.GetSite(ctx, sh.SiteID)
	if err != nil {
		return "", "", err
	}
	owner, err := s.db.GetUserByID(ctx, site.UserID)
	if err != nil {
		return "", "", err
	}
	l := s.layoutFor(site, owner)
	return path.Join(l.docroot, sh.Path), path.Join(s.userHome(guest), sh.Name), nil
}

func (s *Server) userHome(u *store.User) string {
	if u.Home != "" {
		return u.Home
	}
	return path.Join(s.cfg.WWWRoot, u.Login)
}

// applyShare makes the folder, its ACLs and the mount. Every step is
// idempotent, so it also repairs a share after a reboot or mp site fix.
func (s *Server) applyShare(ctx context.Context, sh *store.Share) (*apitypes.ShareStatus, error) {
	target, where, err := s.sharePaths(ctx, sh)
	if err != nil {
		return nil, err
	}
	// The folder belongs to the site owner; setgid keeps the owner's group on
	// new files. The guest and the owner get rwx, inherited by everything
	// created inside, and the web group keeps reading as everywhere in the site.
	if _, err := s.agent.EnsureDirs(ctx, &agent.EnsureDirsRequest{Dirs: []agent.DirSpec{{Path: target, Mode: 0o2770, Owner: sh.OwnerLogin, Group: sh.OwnerLogin}}}); err != nil {
		return nil, fmt.Errorf("folder: %w", err)
	}
	entries := []string{"u:" + sh.Login + ":rwx", "u:" + sh.OwnerLogin + ":rwx", "g:" + s.cfg.WebGroup + ":r-x"}
	if err := s.agent.SetACL(ctx, &agent.SetACLRequest{Path: target, Entries: entries, Default: true, Recursive: true}); err != nil {
		return nil, fmt.Errorf("acl: %w", err)
	}
	// The mount point sits in the guest's root-owned chroot; once mounted it
	// shows the folder's own ownership.
	if _, err := s.agent.EnsureDirs(ctx, &agent.EnsureDirsRequest{Dirs: []agent.DirSpec{{Path: where, Mode: 0o755, Owner: "root", Group: "root"}}}); err != nil {
		return nil, fmt.Errorf("mount point: %w", err)
	}
	unit := store.MountUnit(where)
	text := fmt.Sprintf("# Generated by MonoPanel: shared folder of %s for %s\n[Unit]\nDescription=MonoPanel shared folder %s/%s for %s\nRequiresMountsFor=%s\n\n[Mount]\nWhat=%s\nWhere=%s\nType=none\nOptions=bind\n\n[Install]\nWantedBy=multi-user.target\n",
		sh.Domain, sh.Login, sh.Domain, sh.Path, sh.Login, path.Dir(target), target, where)
	if _, err := s.agent.ApplyConfigSet(ctx, &agent.ApplyConfigSetRequest{Files: []agent.FileSpec{{Path: path.Join(unitDir, unit), Content: text, Mode: 0o644}}, Origin: "share:" + unit}); err != nil {
		return nil, err
	}
	if _, err := s.agent.Service(ctx, "", "daemon-reload"); err != nil {
		return nil, err
	}
	var last *agent.ServiceResponse
	for _, action := range []string{"enable", "start"} {
		res, err := s.agent.Service(ctx, unit, action)
		if err != nil {
			s.db.SetShareStatus(context.WithoutCancel(ctx), sh.ID, "failed", err.Error()) //nolint:errcheck // the error being reported matters more
			return nil, fmt.Errorf("%s %s: %w", action, unit, err)
		}
		last = res
	}
	sh.Status, sh.LastError = last.Status.ActiveState, ""
	s.db.SetShareStatus(context.WithoutCancel(ctx), sh.ID, sh.Status, "") //nolint:errcheck // status is advisory
	return &apitypes.ShareStatus{Share: sh, Mounted: sh.Status == "active", Where: where, Target: target}, nil
}

// removeShare unmounts and forgets a share; the folder and its files stay
// with the site, only the guest's ACL entries go.
func (s *Server) removeShare(ctx context.Context, sh *store.Share) error {
	target, where, err := s.sharePaths(ctx, sh)
	if err != nil {
		return err
	}
	unit := store.MountUnit(where)
	s.agent.Service(ctx, unit, "stop")    //nolint:errcheck // may not be mounted
	s.agent.Service(ctx, unit, "disable") //nolint:errcheck // may not be enabled
	if _, err := s.agent.RemovePaths(ctx, &agent.RemovePathsRequest{Paths: []string{path.Join(unitDir, unit)}}); err != nil {
		return err
	}
	s.agent.Service(ctx, "", "daemon-reload") //nolint:errcheck // best effort
	// The mount point is an empty root-owned directory once unmounted; a
	// leftover is only untidy, so it does not stop the removal.
	if _, err := s.agent.RemovePaths(ctx, &agent.RemovePathsRequest{Paths: []string{where}}); err != nil {
		s.log.Warn("share: mount point not removed", "path", where, "err", err)
	}
	if err := s.agent.SetACL(ctx, &agent.SetACLRequest{Path: target, Remove: []string{"u:" + sh.Login}, Default: true, Recursive: true}); err != nil {
		s.log.Warn("share: guest ACL not removed", "path", target, "guest", sh.Login, "err", err)
	}
	return s.db.DeleteShare(ctx, sh.ID)
}

// shareStatus reports a share with its mount state.
func (s *Server) shareStatus(ctx context.Context, sh *store.Share) *apitypes.ShareStatus {
	out := &apitypes.ShareStatus{Share: sh}
	target, where, err := s.sharePaths(ctx, sh)
	if err != nil {
		return out
	}
	out.Target, out.Where = target, where
	if res, err := s.agent.Service(ctx, store.MountUnit(where), "status"); err == nil {
		out.Mounted = res.Status.ActiveState == "active"
	}
	return out
}

// siteNoPHPPaths lists the shared folders of a site where PHP must not run.
func (s *Server) siteNoPHPPaths(ctx context.Context, siteID int64) []string {
	shares, err := s.db.ListSiteShares(ctx, siteID)
	if err != nil {
		return nil
	}
	var out []string
	for _, sh := range shares {
		if sh.NoPHP {
			out = append(out, sh.Path)
		}
	}
	return out
}

// reapplyShareACLs restores the guests' ACLs after mp site fix rewrote the
// site tree's entries.
func (s *Server) reapplyShareACLs(ctx context.Context, jc *jobs.Context, siteID int64) {
	shares, err := s.db.ListSiteShares(ctx, siteID)
	if err != nil {
		return
	}
	for _, sh := range shares {
		if _, err := s.applyShare(ctx, sh); err != nil {
			jc.Logf("warning: shared folder %s for %s: %v", sh.Path, sh.Login, err)
			continue
		}
		jc.Logf("shared folder %s for %s: ACLs and mount restored", sh.Path, sh.Login)
	}
}

// removeSiteShares unmounts every guest's view of a site before the site
// goes; the mounts would otherwise keep the purged folder alive.
func (s *Server) removeSiteShares(ctx context.Context, jc *jobs.Context, siteID int64) error {
	shares, err := s.db.ListSiteShares(ctx, siteID)
	if err != nil {
		return err
	}
	entry := false
	for _, sh := range shares {
		if err := s.removeShare(ctx, sh); err != nil {
			return fmt.Errorf("shared folder %s for %s: %w", sh.Path, sh.Login, err)
		}
		jc.Logf("shared folder %s for %s removed", sh.Path, sh.Login)
		entry = entry || sh.Entry
	}
	if entry {
		if err := s.ensureSSHConfig(ctx); err != nil {
			jc.Logf("warning: sshd drop-in not refreshed: %v", err)
		}
	}
	return nil
}

// removeUserShares unmounts the folders a guest reaches before its home goes;
// a site that denied PHP in such a folder is re-applied without the rule.
func (s *Server) removeUserShares(ctx context.Context, jc *jobs.Context, userID int64) error {
	shares, err := s.db.ListShares(ctx, userID)
	if err != nil {
		return err
	}
	reapply := map[int64]string{}
	entry := false
	for _, sh := range shares {
		if err := s.removeShare(ctx, sh); err != nil {
			return fmt.Errorf("shared folder %s: %w", sh.Name, err)
		}
		jc.Logf("shared folder %s (%s/%s) removed", sh.Name, sh.Domain, sh.Path)
		if sh.NoPHP {
			reapply[sh.SiteID] = sh.Domain
		}
		entry = entry || sh.Entry
	}
	if entry {
		if err := s.ensureSSHConfig(ctx); err != nil {
			jc.Logf("warning: sshd drop-in not refreshed: %v", err)
		}
	}
	for id, domain := range reapply {
		if _, err := s.jobs.Enqueue(ctx, "site.apply", sitePayload{SiteID: id}, jobs.WithLockKey("site:"+domain), jobs.WithRequestedBy("system")); err != nil {
			jc.Logf("warning: site %s not re-applied after the shared folder went: %v", domain, err)
		}
	}
	return nil
}

func (s *Server) registerShares() {
	huma.Register(s.api, huma.Operation{
		OperationID: "shares-list", Method: http.MethodGet, Path: "/users/{login}/shares", Summary: "Folders of other accounts' sites this account reaches over SFTP", Tags: []string{"users"}, Security: secured,
	}, func(ctx context.Context, in *loginInputPath) (*shareListOutput, error) {
		u, err := s.loadUserFor(ctx, in.Login)
		if err != nil {
			return nil, err
		}
		shares, err := s.db.ListShares(ctx, u.ID)
		if err != nil {
			return nil, err
		}
		out := make([]*apitypes.ShareStatus, 0, len(shares))
		for _, sh := range shares {
			out = append(out, s.shareStatus(ctx, sh))
		}
		return &shareListOutput{Body: out}, nil
	})

	huma.Register(s.api, huma.Operation{
		OperationID: "shares-create", Method: http.MethodPost, Path: "/users/{login}/shares", Summary: "Give the account a folder of another account's site: bind mount into its home plus ACLs (admin)", Tags: []string{"users"}, Security: secured, Metadata: adminOnly,
	}, func(ctx context.Context, in *shareCreateInput) (*shareOutput, error) {
		p := principalFrom(ctx)
		guest, err := s.loadUserFor(ctx, in.Login)
		if err != nil {
			return nil, err
		}
		if guest.UnixUID == nil || guest.Status != store.UserActive {
			return nil, huma.Error422UnprocessableEntity("the guest must be an active user with a provisioned unix account")
		}
		site, err := s.db.GetSiteByDomain(ctx, strings.ToLower(strings.TrimSpace(in.Body.Site)))
		if errors.Is(err, store.ErrNotFound) {
			return nil, huma.Error422UnprocessableEntity("site not found")
		} else if err != nil {
			return nil, err
		}
		if site.UserID == guest.ID {
			return nil, huma.Error422UnprocessableEntity("the site already belongs to this account")
		}
		// The path is taken as written: cleaning "../x" into "x" would hide
		// an attempt to leave the docroot, so it is refused instead.
		rel := strings.Trim(in.Body.Path, "/")
		if rel == "" || strings.Contains(rel, "..") || path.Clean(rel) != rel || !sharePathRe.MatchString(rel) {
			return nil, huma.Error422UnprocessableEntity("path must be a folder inside the site, like kaspy or upload/exchange")
		}
		name := in.Body.Name
		if name == "" {
			name = strings.ToLower(path.Base(rel))
		}
		if !appNameRe.MatchString(name) {
			return nil, huma.Error422UnprocessableEntity("name must be lowercase letters, digits, - or _ (pass name explicitly)")
		}
		if name == "data" || name == ".ssh" {
			return nil, huma.Error422UnprocessableEntity("name " + name + " is taken by the account's own layout")
		}
		owner, err := s.db.GetUserByID(ctx, site.UserID)
		if err != nil {
			return nil, err
		}
		if in.Body.Entry && guest.Shell {
			return nil, huma.Error422UnprocessableEntity("an entry folder is for SFTP-only accounts; an account with a shell signs in wherever it likes")
		}
		sh := &store.Share{UserID: guest.ID, Login: guest.Login, SiteID: site.ID, Domain: site.Domain, OwnerLogin: owner.Login, Path: rel, Name: name, NoPHP: in.Body.NoPHP, Entry: in.Body.Entry}
		if err := s.db.CreateShare(ctx, sh); err != nil {
			if errors.Is(err, store.ErrExists) {
				return nil, huma.Error409Conflict("the account already has a shared folder named " + name)
			}
			return nil, err
		}
		st, err := s.applyShare(ctx, sh)
		if err != nil {
			s.db.DeleteShare(context.WithoutCancel(ctx), sh.ID) //nolint:errcheck // nothing to keep
			return nil, huma.Error502BadGateway(err.Error())
		}
		if sh.Entry {
			if err := s.ensureSSHConfig(ctx); err != nil {
				return nil, huma.Error502BadGateway("sshd: " + err.Error())
			}
		}
		if sh.NoPHP {
			job, err := s.jobs.Enqueue(ctx, "site.apply", sitePayload{SiteID: site.ID}, jobs.WithLockKey("site:"+site.Domain), jobs.WithRequestedBy(p.Login))
			if err != nil {
				return nil, err
			}
			st.JobID = job.ID
		}
		s.db.Audit(ctx, store.AuditEntry{Actor: p.Login, Action: "share.create", Target: guest.Login, IP: requestInfo(ctx).IP, Details: map[string]any{"site": site.Domain, "path": rel, "name": name, "no_php": sh.NoPHP, "entry": sh.Entry}})
		return &shareOutput{Status: http.StatusCreated, Body: st}, nil
	})

	huma.Register(s.api, huma.Operation{
		OperationID: "shares-update", Method: http.MethodPatch, Path: "/users/{login}/shares/{name}", Summary: "Make the folder the account's SFTP entry point, or stop that: the session starts inside the folder instead of the home (admin)", Tags: []string{"users"}, Security: secured, Metadata: adminOnly,
	}, func(ctx context.Context, in *shareUpdateInput) (*shareOutput, error) {
		p := principalFrom(ctx)
		guest, err := s.loadUserFor(ctx, in.Login)
		if err != nil {
			return nil, err
		}
		sh, err := s.db.GetShare(ctx, guest.ID, in.Name)
		if errors.Is(err, store.ErrNotFound) {
			return nil, huma.Error404NotFound("shared folder not found")
		} else if err != nil {
			return nil, err
		}
		if in.Body.Entry && guest.Shell {
			return nil, huma.Error422UnprocessableEntity("an entry folder is for SFTP-only accounts; an account with a shell signs in wherever it likes")
		}
		if err := s.db.SetShareEntry(ctx, sh, in.Body.Entry); err != nil {
			return nil, err
		}
		if err := s.ensureSSHConfig(ctx); err != nil {
			return nil, huma.Error502BadGateway("sshd: " + err.Error())
		}
		s.db.Audit(ctx, store.AuditEntry{Actor: p.Login, Action: "share.update", Target: guest.Login, IP: requestInfo(ctx).IP, Details: map[string]any{"name": sh.Name, "entry": sh.Entry}})
		return &shareOutput{Status: http.StatusOK, Body: s.shareStatus(ctx, sh)}, nil
	})

	huma.Register(s.api, huma.Operation{
		OperationID: "shares-delete", Method: http.MethodDelete, Path: "/users/{login}/shares/{name}", Summary: "Take the folder away: unmount and drop the guest's ACLs; the files stay with the site (admin)", Tags: []string{"users"}, Security: secured, Metadata: adminOnly,
	}, func(ctx context.Context, in *shareNameInput) (*shareOutput, error) {
		p := principalFrom(ctx)
		guest, err := s.loadUserFor(ctx, in.Login)
		if err != nil {
			return nil, err
		}
		sh, err := s.db.GetShare(ctx, guest.ID, in.Name)
		if errors.Is(err, store.ErrNotFound) {
			return nil, huma.Error404NotFound("shared folder not found")
		} else if err != nil {
			return nil, err
		}
		if err := s.removeShare(ctx, sh); err != nil {
			return nil, huma.Error502BadGateway(err.Error())
		}
		if sh.Entry {
			if err := s.ensureSSHConfig(ctx); err != nil {
				return nil, huma.Error502BadGateway("sshd: " + err.Error())
			}
		}
		st := &apitypes.ShareStatus{Share: sh}
		if sh.NoPHP {
			job, err := s.jobs.Enqueue(ctx, "site.apply", sitePayload{SiteID: sh.SiteID}, jobs.WithLockKey("site:"+sh.Domain), jobs.WithRequestedBy(p.Login))
			if err != nil {
				return nil, err
			}
			st.JobID = job.ID
		}
		s.db.Audit(ctx, store.AuditEntry{Actor: p.Login, Action: "share.delete", Target: guest.Login, IP: requestInfo(ctx).IP, Details: map[string]any{"site": sh.Domain, "path": sh.Path, "name": sh.Name}})
		return &shareOutput{Status: http.StatusOK, Body: st}, nil
	})
}
