#!/usr/bin/env bash
# Local side of the MonoPanel testbed: drives scripts/testbed/pve.sh on the
# Proxmox host over ssh, keeps ssh aliases for the VMs, deploys the panel to
# them and runs the end-to-end tests. Settings come from .dev/testbed.env
# (git-ignored):
#
#   PVE_HOST=root@pve.example.com     # ssh destination of the Proxmox host
#   TB_PREFIX=192.0.2                 # LAN of the VMs, first three octets
#   TB_GATEWAY=192.0.2.1              # optional, default .1
#   TB_IP_BASE=200                    # VM n gets TB_PREFIX.(TB_IP_BASE+n)
#   TB_SSH_KEY_FILE=~/.ssh/id_ed25519 # private key; its .pub goes to root@vm
#
#   testbed.sh up|reset|down [name...]   VMs on the Proxmox host
#   testbed.sh status | names            what exists
#   testbed.sh ssh-config                write ~/.ssh/config.d/monopanel-testbed
#   testbed.sh deploy <name> [--binary]  package (default) or binary + bootstrap
#   testbed.sh e2e <name>                make e2e against the VM
#   testbed.sh matrix [name...]          reset + deploy + e2e for each VM, summary
#   testbed.sh migrate <src> <dst>       move an account between two VMs and verify
set -euo pipefail
export PATH="$HOME/go/bin:$HOME/.local/go/bin:$HOME/.local/node/bin:$PATH"

root=$(cd "$(dirname "$0")/../.." && pwd)
env_file="$root/.dev/testbed.env"
[ -f "$env_file" ] || { echo "testbed.sh: create $env_file first (see the header of this script)" >&2; exit 2; }
# shellcheck disable=SC1090
. "$env_file"
: "${PVE_HOST:?PVE_HOST in $env_file}"
: "${TB_PREFIX:?TB_PREFIX in $env_file}"
: "${TB_SSH_KEY_FILE:=$HOME/.ssh/id_ed25519}"
TB_SSH_KEY_FILE=${TB_SSH_KEY_FILE/#\~/$HOME}
[ -f "$TB_SSH_KEY_FILE.pub" ] || { echo "testbed.sh: $TB_SSH_KEY_FILE.pub not found" >&2; exit 2; }

ssh_cfg="$HOME/.ssh/config.d/monopanel-testbed"
logs="$root/.dev/testbed/logs"
mkdir -p "$logs"

log() { printf '\033[36m[%s]\033[0m %s\n' "$(date +%H:%M:%S)" "$*" >&2; }

# remote <args...>: run pve.sh on the Proxmox host with our settings.
remote() {
	local vars="" v
	for v in TB_PREFIX TB_GATEWAY TB_DNS TB_IP_BASE TB_VMID_BASE TB_BRIDGE TB_STORAGE TB_CORES TB_MEMORY TB_DISK TB_CIDR $(compgen -v TB_IMAGE_URL_ || true); do
		[ -n "${!v:-}" ] && vars+="$v=$(printf %q "${!v}") "
	done
	vars+="TB_SSH_KEY=$(printf %q "$(cut -d' ' -f1,2 "$TB_SSH_KEY_FILE.pub")")"
	# shellcheck disable=SC2029
	ssh "$PVE_HOST" "$vars bash -s -- $(printf '%q ' "$@")" <"$root/scripts/testbed/pve.sh"
}

# ssh_config writes one Host stanza per VM. Rebuilt VMs get new host keys, so
# they live in their own known_hosts file that is simply removed on `down`.
ssh_config() {
	mkdir -p "$(dirname "$ssh_cfg")"
	{
		echo "# MonoPanel testbed, generated by scripts/testbed/testbed.sh ssh-config"
		remote list | while read -r name _ ip; do
			cat <<STANZA
Host mp-$name
    HostName $ip
    User root
    IdentityFile $TB_SSH_KEY_FILE
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ~/.ssh/known_hosts.monopanel-testbed
    LogLevel ERROR
STANZA
		done
	} >"$ssh_cfg"
	if ! grep -qs "^Include ~/.ssh/config.d/monopanel-testbed" "$HOME/.ssh/config"; then
		# Include has to come before the first Host block to apply globally.
		{ echo "Include ~/.ssh/config.d/monopanel-testbed"; cat "$HOME/.ssh/config" 2>/dev/null; } >"$HOME/.ssh/config.new"
		mv "$HOME/.ssh/config.new" "$HOME/.ssh/config"
	fi
	log "wrote $ssh_cfg"
}

# deploy <name> [--binary]: build, copy, run bootstrap.sh on the VM.
deploy() {
	local name=$1 how=${2:-} vm ip family pkg
	vm="mp-$name"
	ip=$(ssh "$vm" 'hostname -I | cut -d" " -f1')
	family=$(ssh "$vm" '. /etc/os-release; case " $ID $ID_LIKE " in *debian*|*ubuntu*) echo deb;; *) echo rpm;; esac')
	log "$vm ($ip, $family): $([ -n "${TB_PREBUILT:-}" ] && echo "deploying" || echo "building")"
	if [ "$how" = "--binary" ]; then
		[ -n "${TB_PREBUILT:-}" ] || (cd "$root" && make -s build)
		scp -q "$root/dist/monopanel" "$vm:/tmp/monopanel"
		pkg=/tmp/monopanel
	else
		[ -n "${TB_PREBUILT:-}" ] || (cd "$root" && make -s "$family" >/dev/null)
		pkg=$(cd "$root/dist" && ls -t monopanel*."$family" | head -1)
		[ "$family" = rpm ] && pkg=$(cd "$root/dist" && ls -t monopanel-*.x86_64.rpm | head -1)
		[ "$family" = deb ] && pkg=$(cd "$root/dist" && ls -t monopanel_*_amd64.deb | head -1)
		scp -q "$root/dist/$pkg" "$vm:/tmp/$pkg"
		pkg="/tmp/$pkg"
	fi
	scp -q "$root/scripts/testbed/bootstrap.sh" "$vm:/tmp/bootstrap.sh"
	# shellcheck disable=SC2029
	ssh "$vm" "TB_PHP=${TB_PHP:-} TB_DB=${TB_DB:-} TB_EXTRA=${TB_EXTRA:-} bash /tmp/bootstrap.sh $pkg $ip"
}

e2e() {
	local name=$1
	(cd "$root" && MONOPANEL_INSECURE=1 make -s e2e HOST="mp-$name")
}

# matrix: the whole cycle per VM, in parallel, with one log per VM and a
# table. TB_NO_RESET=1 skips the rollback (for VMs that are fresh anyway).
matrix() {
	local n pids=() names=("$@") results=()
	log "building the packages once for ${names[*]}"
	(cd "$root" && make -s deb >/dev/null && make -s rpm >/dev/null)
	export TB_PREBUILT=1
	for n in "${names[@]}"; do
		(
			exec >"$logs/$n.log" 2>&1
			[ -n "${TB_NO_RESET:-}" ] || remote reset "$n"
			deploy "$n"
			e2e "$n"
		) &
		pids+=($!)
	done
	for i in "${!names[@]}"; do
		if wait "${pids[$i]}"; then results+=("${names[$i]} ok"); else results+=("${names[$i]} FAIL"); fi
	done
	echo
	printf '%-12s %s\n' VM RESULT
	printf '%s\n' "${results[@]}" | awk '{printf "%-12s %s\n", $1, $2}'
	echo "logs: $logs/"
	printf '%s\n' "${results[@]}" | grep -q FAIL && return 1 || return 0
}

cmd=${1:-status}; shift || true
# shellcheck disable=SC2046 # VM names are single words
case "$cmd" in
up) remote up "$@"; ssh_config ;;
reset | down) remote "$cmd" "$@"; [ "$cmd" = down ] && [ $# -eq 0 ] && rm -f "$HOME/.ssh/known_hosts.monopanel-testbed"; true ;;
status | names | list) remote "$cmd" ;;
ssh-config) ssh_config ;;
deploy) [ $# -ge 1 ] || { echo "usage: testbed.sh deploy <name> [--binary]" >&2; exit 2; }; deploy "$@" ;;
e2e) [ $# -eq 1 ] || { echo "usage: testbed.sh e2e <name>" >&2; exit 2; }; e2e "$1" ;;
matrix) [ $# -gt 0 ] || set -- $(remote names); matrix "$@" ;;
migrate) [ $# -eq 2 ] || { echo "usage: testbed.sh migrate <source> <target>" >&2; exit 2; }; exec "$root/scripts/testbed/migrate.sh" "$1" "$2" ;;
*) echo "usage: testbed.sh up|reset|down [name...] | status | ssh-config | deploy <name> | e2e <name> | matrix [name...] | migrate <src> <dst>" >&2; exit 2 ;;
esac
